name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote | grep origin || git remote add origin https://github.com/kkayaiirem/First-Flutter-Dashboard.git
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp -r build/web/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
      